"""
tests/test_scanner.py
=====================
Tests for VideoConverter/scanner.py.

Requires test fixture videos generated by make_fixtures.ps1.
Run:  pytest VideoConverter/tests/test_scanner.py -v
"""

import os
import shutil
import sqlite3
import sys
from unittest.mock import patch

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import db
import scanner
from pathlib import Path

FIXTURES_DIR = Path(__file__).parent / "fixtures"

pytestmark = pytest.mark.skipif(
    not FIXTURES_DIR.exists() or not any(FIXTURES_DIR.iterdir()),
    reason="Run VideoConverter/tests/make_fixtures.ps1 first",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _collect(root, **kwargs):
    """
    Run scanner.walk(root) and return a tuple:
      (folder_events, done_event, warning_events, error_events)
    """
    folders  = []
    done     = None
    warnings = []
    errors   = []
    for event in scanner.walk(str(root)):
        t = event.get("type")
        if t == "folder":
            folders.append(event)
        elif t == "hash_match_done":
            target = (event.get("full_path") or "").replace("\\", "/")
            for ev in folders:
                for f in ev.get("files", []):
                    if (f.get("full_path") or "").replace("\\", "/") == target:
                        f["status"] = "done"
                        if event.get("codec"):
                            f["codec"] = event.get("codec")
                        if event.get("duration"):
                            f["duration"] = event.get("duration")
                        if event.get("bitrate_kbps") is not None:
                            f["bitrate_kbps"] = event.get("bitrate_kbps")
                        if event.get("video_track_count") is not None:
                            f["video_track_count"] = event.get("video_track_count")
                        if event.get("audio_track_count") is not None:
                            f["audio_track_count"] = event.get("audio_track_count")
                        if event.get("subtitle_track_count") is not None:
                            f["subtitle_track_count"] = event.get("subtitle_track_count")
                        if event.get("output") is not None:
                            f["output"] = event.get("output")
                        if event.get("saved") is not None:
                            f["saved"] = event.get("saved")
                        if event.get("pct") is not None:
                            f["pct"] = event.get("pct")
                        break
        elif t == "done":
            done = event
        elif t == "warning":
            warnings.append(event)
        elif t == "error":
            errors.append(event)
    return folders, done, warnings, errors


def _all_files(folder_events):
    """Flatten all file dicts from a list of folder events."""
    return [f for ev in folder_events for f in ev["files"]]


# ---------------------------------------------------------------------------
# DB fixture — fresh empty SQLite DB for each test
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def fresh_db(tmp_path):
    """Ensure every test runs against a clean, empty in-process DB."""
    db_path = str(tmp_path / "test.db")
    db.init_db(db_path)
    yield db_path


# ---------------------------------------------------------------------------
# scanner.walk — content tests
# ---------------------------------------------------------------------------

def test_walk_finds_h264_files():
    """All six H.264 fixture files appear; hevc_skip.mkv also appears (HEVC re-encoding is allowed)."""
    folders, done, _, _ = _collect(FIXTURES_DIR)
    files = _all_files(folders)
    names = {f["name"] for f in files}

    h264_names = {
        "h264_short.mkv",
        "h264_long.mkv",
        "h264_tiny.mkv",
        "h264_multitrack.mkv",
        "h264_hi10.mkv",
        "h264_mp4_aac.mp4",
    }
    assert h264_names.issubset(names), f"Missing H.264 files: {h264_names - names}"


def test_walk_includes_hevc():
    """hevc_skip.mkv must appear in scan results — HEVC files are re-encodeable."""
    folders, _, _, _ = _collect(FIXTURES_DIR)
    names = {f["name"] for f in _all_files(folders)}
    assert "hevc_skip.mkv" in names


def test_walk_finds_all_video_extensions():
    """.mp4 file found alongside .mkv files."""
    folders, _, _, _ = _collect(FIXTURES_DIR)
    names = {f["name"] for f in _all_files(folders)}
    mp4_names = {n for n in names if n.endswith(".mp4")}
    mkv_names = {n for n in names if n.endswith(".mkv")}
    assert len(mp4_names) >= 1
    assert len(mkv_names) >= 1


def test_walk_streams_populated():
    """Probe events include populated stream details for h264_short.mkv."""
    short_probe = None
    target_suffix = "/h264_short.mkv"
    for event in scanner.walk(str(FIXTURES_DIR)):
        if event.get("type") != "probe":
            continue
        full_path = (event.get("full_path") or "").replace("\\", "/")
        if full_path.endswith(target_suffix):
            short_probe = event
            break

    assert short_probe is not None, "Expected probe event for h264_short.mkv"
    streams = short_probe.get("streams") or {}
    video = streams.get("video") or {}
    assert video.get("codec") == "H264"
    assert video.get("resolution") != "unknown"


def test_walk_hi10_flagged():
    """Probe event for h264_hi10.mkv has is_hi10 == True."""
    hi10_probe = None
    target_suffix = "/h264_hi10.mkv"
    for event in scanner.walk(str(FIXTURES_DIR)):
        if event.get("type") != "probe":
            continue
        full_path = (event.get("full_path") or "").replace("\\", "/")
        if full_path.endswith(target_suffix):
            hi10_probe = event
            break

    assert hi10_probe is not None, "Expected probe event for h264_hi10.mkv"
    assert hi10_probe.get("is_hi10") is True


def test_walk_done_event():
    """Final event is type='done' with total_files matching streamed folder files."""
    folders, done, _, _ = _collect(FIXTURES_DIR)
    assert done is not None
    assert done["type"] == "done"
    assert done["total_files"] == len(_all_files(folders))
    assert done["total_mb"] > 0


def test_walk_emits_phase1_scan_progress(tmp_path):
    """Large candidate sets should emit scan_progress heartbeats during phase 1."""
    for i in range(55):
        (tmp_path / f"clip_{i:03d}.mkv").write_bytes(b"\x00")

    fake_probe = {
        "streams": [{
            "codec_type": "video",
            "codec_name": "h264",
            "width": 1920,
            "height": 1080,
            "r_frame_rate": "24/1",
            "profile": "",
            "pix_fmt": "yuv420p",
            "bits_per_raw_sample": "8",
        }],
        "format": {"duration": "10.0", "bit_rate": "5000000"},
    }

    with patch("scanner._ffprobe", return_value=fake_probe):
        progress_seen = False
        for event in scanner.walk(str(tmp_path)):
            if event.get("type") == "scan_progress":
                progress_seen = True
                break

    assert progress_seen, "Expected at least one phase-1 scan_progress event"


def test_scan_progress_includes_current_folder(tmp_path):
    """scan_progress events should include the relative folder currently being scanned."""
    sub = tmp_path / "SeasonA"
    sub.mkdir()
    for i in range(55):
        (sub / f"clip_{i:03d}.mkv").write_bytes(b"\x01")

    fake_probe = {
        "streams": [{
            "codec_type": "video",
            "codec_name": "h264",
            "width": 1280,
            "height": 720,
            "r_frame_rate": "24/1",
            "profile": "",
            "pix_fmt": "yuv420p",
            "bits_per_raw_sample": "8",
        }],
        "format": {"duration": "8.0", "bit_rate": "3000000"},
    }

    with patch("scanner._ffprobe", return_value=fake_probe):
        seen_folder = False
        for event in scanner.walk(str(tmp_path)):
            if event.get("type") != "scan_progress":
                continue
            if event.get("current_folder") == "SeasonA":
                seen_folder = True
                break

    assert seen_folder, "Expected scan_progress to report current_folder='SeasonA'"


# ---------------------------------------------------------------------------
# scanner.walk — folder event shape
# ---------------------------------------------------------------------------

def test_walk_folder_events(tmp_path):
    """Two subdirectories each produce one folder event with correct rel path."""
    sub_a = tmp_path / "ShowA"
    sub_b = tmp_path / "ShowB"
    sub_a.mkdir()
    sub_b.mkdir()
    shutil.copy(FIXTURES_DIR / "h264_short.mkv",   sub_a / "ep01.mkv")
    shutil.copy(FIXTURES_DIR / "h264_mp4_aac.mp4", sub_b / "ep02.mp4")

    folders, done, _, _ = _collect(tmp_path)

    folder_names = {ev["folder"] for ev in folders}
    assert "ShowA" in folder_names
    assert "ShowB" in folder_names
    assert done["total_files"] == 2


# ---------------------------------------------------------------------------
# scanner.walk — corrupt / empty file handling
# ---------------------------------------------------------------------------

def test_walk_corrupt_file_emits_warning(tmp_path):
    """A zero-byte .mkv yields a warning event; walk continues normally."""
    # Real file alongside the bad one so the folder is still yielded
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", tmp_path / "good.mkv")
    (tmp_path / "bad.mkv").write_bytes(b"")

    folders, done, warnings, _ = _collect(tmp_path)

    # Warning for the empty file
    assert any("bad.mkv" in w["path"] for w in warnings)
    # Good file still scanned
    names = {f["name"] for f in _all_files(folders)}
    assert "good.mkv" in names
    assert done["total_files"] == 1


# ---------------------------------------------------------------------------
# scanner.walk — DB skip / requeue behaviour
# ---------------------------------------------------------------------------

def test_walk_skips_db_done(tmp_path, fresh_db):
    """File with status='done' in DB is included as a read-only done row."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    mtime  = dest.stat().st_mtime
    rec_id = db.upsert_pending(str(dest), mtime)
    db.mark_running(rec_id, "2026-01-01T00:00:00Z")
    db.mark_done(
        rec_id,
        str(tmp_path / "converted" / "h264_short.mkv"),
        output_size_mb=0.5,
        saved_mb=0.7,
        saved_pct=58,
        completed_at="2026-01-01T00:01:00Z",
    )

    folders, done, _, _ = _collect(tmp_path)
    assert done["total_files"] == 0
    files = _all_files(folders)
    assert len(files) == 1
    assert files[0]["name"] == "h264_short.mkv"
    assert files[0]["status"] == "done"


def test_walk_requeues_replaced_file(tmp_path, fresh_db):
    """Same path with newer mtime still resolves to current done-row state."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    mtime  = dest.stat().st_mtime
    rec_id = db.upsert_pending(str(dest), mtime)
    db.mark_running(rec_id, "2026-01-01T00:00:00Z")
    db.mark_done(
        rec_id,
        str(tmp_path / "converted" / "h264_short.mkv"),
        output_size_mb=0.5,
        saved_mb=0.7,
        saved_pct=58,
        completed_at="2026-01-01T00:01:00Z",
    )

    # Simulate in-place replacement by nudging mtime forward
    new_mtime = mtime + 1.0
    os.utime(str(dest), (new_mtime, new_mtime))

    folders, done, _, _ = _collect(tmp_path)
    assert done["total_files"] == 0
    files = _all_files(folders)
    assert len(files) == 1
    assert files[0]["name"] == "h264_short.mkv"
    assert files[0]["status"] == "done"


def test_walk_hash_matches_done_and_cleans_stale_pending(tmp_path, fresh_db):
    """Pending rows shadowing a hash-matched done record are resolved and deleted."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    old_mtime = dest.stat().st_mtime
    rec_done = db.upsert_pending(str(dest), old_mtime)
    db.mark_running(rec_done, "2026-01-01T00:00:00Z")
    db.mark_done(
        rec_done,
        str(tmp_path / "converted" / "h264_short.mp4"),
        output_size_mb=0.5,
        saved_mb=0.7,
        saved_pct=58,
        completed_at="2026-01-01T00:01:00Z",
        output_hash=db.hash_file_head(str(dest)),
    )

    new_mtime = old_mtime + 1.0
    os.utime(str(dest), (new_mtime, new_mtime))
    db.upsert_pending(str(dest), new_mtime)

    folders, done, _, _ = _collect(tmp_path)
    assert done["total_files"] == 0
    files = _all_files(folders)
    assert len(files) == 1
    assert files[0]["name"] == "h264_short.mkv"
    assert files[0]["status"] == "done"

    conn = sqlite3.connect(fresh_db)
    try:
        rows = conn.execute(
            "SELECT id, status FROM conversions WHERE source_path = ? ORDER BY id",
            (str(dest).replace('\\', '/'),),
        ).fetchall()
    finally:
        conn.close()

    assert [(row[0], row[1]) for row in rows] == [(rec_done, "done")]


def test_walk_does_not_hash_before_scan_done(tmp_path, fresh_db):
    """Phase-1 scan should avoid hash_file_head reads before scan_done is emitted."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    mtime = dest.stat().st_mtime
    db.upsert_pending(str(dest), mtime)

    with patch("scanner.db.hash_file_head", return_value=None) as mock_hash:
        for event in scanner.walk(str(tmp_path)):
            if event.get("type") == "scan_done":
                assert mock_hash.call_count == 0
                break


def test_walk_running_emits_warning(tmp_path, fresh_db):
    """File with status='running' in DB emits a warning and is not yielded."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    mtime  = dest.stat().st_mtime
    rec_id = db.upsert_pending(str(dest), mtime)
    db.mark_running(rec_id, "2026-01-01T00:00:00Z")

    folders, done, warnings, _ = _collect(tmp_path)
    assert done["total_files"] == 0
    assert folders == []
    assert any(str(dest).replace("\\", "/") in w["path"].replace("\\", "/")
               for w in warnings)


# ---------------------------------------------------------------------------
# scanner.walk — error handling
# ---------------------------------------------------------------------------

def test_walk_invalid_root():
    """Non-existent root yields a single error event and no folder events."""
    folders, done, warnings, errors = _collect("/nonexistent/path/xyz_abc")
    assert errors != []
    assert folders == []
    assert done is None


# ---------------------------------------------------------------------------
# Flask API route tests
# ---------------------------------------------------------------------------

@pytest.fixture
def client():
    # Import app after db.init_db has been called by fresh_db (autouse),
    # so app.py's module-level db.init_db(DB_PATH) is overridden for test.
    import app as flask_app
    flask_app.app.testing = True
    with flask_app.app.test_client() as c:
        yield c


def test_api_scan_invalid_path(client):
    """GET /api/scan with a missing path returns 400."""
    resp = client.get("/api/scan?path=/nonexistent/path/xyz_abc_123")
    assert resp.status_code == 400


def test_api_scan_no_path_param(client):
    """GET /api/scan with no path param returns 400."""
    resp = client.get("/api/scan")
    assert resp.status_code == 400


def test_api_scan_sse_content_type(client):
    """GET /api/scan on a valid directory returns text/event-stream."""
    resp = client.get(f"/api/scan?path={FIXTURES_DIR!s}")
    assert resp.status_code == 200
    assert "text/event-stream" in resp.content_type


# ---------------------------------------------------------------------------
# AV1 codec skip
# ---------------------------------------------------------------------------

def test_walk_skips_av1(tmp_path):
    """Files whose first video stream is AV1 are included in scan results."""
    from unittest.mock import patch

    av1_file = tmp_path / "av1_video.mkv"
    av1_file.write_bytes(b"\x00" * 100)   # dummy bytes — ffprobe is mocked

    av1_probe_result = {
        "streams": [{
            "codec_type": "video",
            "codec_name": "av1",
            "width": 1920,
            "height": 1080,
            "r_frame_rate": "24/1",
            "profile": "",
            "pix_fmt": "yuv420p",
            "bits_per_raw_sample": "8",
        }],
        "format": {"duration": "120.0", "bit_rate": "5000000"},
    }

    with patch("scanner._ffprobe", return_value=av1_probe_result):
        folders, done, warnings, errors = _collect(str(tmp_path))

    all_names = {f["name"] for f in _all_files(folders)}
    assert "av1_video.mkv" in all_names
