"""
tests/test_scanner.py
=====================
Tests for VideoConverter/scanner.py.

Requires test fixture videos generated by make_fixtures.ps1.
Run:  pytest VideoConverter/tests/test_scanner.py -v
"""

import os
import shutil
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import db
import scanner
from pathlib import Path

FIXTURES_DIR = Path(__file__).parent / "fixtures"

pytestmark = pytest.mark.skipif(
    not FIXTURES_DIR.exists() or not any(FIXTURES_DIR.iterdir()),
    reason="Run VideoConverter/tests/make_fixtures.ps1 first",
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _collect(root, **kwargs):
    """
    Run scanner.walk(root) and return a tuple:
      (folder_events, done_event, warning_events, error_events)
    """
    folders  = []
    done     = None
    warnings = []
    errors   = []
    for event in scanner.walk(str(root)):
        t = event.get("type")
        if t == "folder":
            folders.append(event)
        elif t == "done":
            done = event
        elif t == "warning":
            warnings.append(event)
        elif t == "error":
            errors.append(event)
    return folders, done, warnings, errors


def _all_files(folder_events):
    """Flatten all file dicts from a list of folder events."""
    return [f for ev in folder_events for f in ev["files"]]


# ---------------------------------------------------------------------------
# DB fixture — fresh empty SQLite DB for each test
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def fresh_db(tmp_path):
    """Ensure every test runs against a clean, empty in-process DB."""
    db_path = str(tmp_path / "test.db")
    db.init_db(db_path)
    yield db_path


# ---------------------------------------------------------------------------
# scanner.walk — content tests
# ---------------------------------------------------------------------------

def test_walk_finds_h264_files():
    """All six H.264 fixture files appear; hevc_skip.mkv must not."""
    folders, done, _, _ = _collect(FIXTURES_DIR)
    files = _all_files(folders)
    names = {f["name"] for f in files}

    h264_names = {
        "h264_short.mkv",
        "h264_long.mkv",
        "h264_tiny.mkv",
        "h264_multitrack.mkv",
        "h264_hi10.mkv",
        "h264_mp4_aac.mp4",
    }
    assert h264_names == names


def test_walk_skips_hevc():
    """hevc_skip.mkv must never appear in any folder event."""
    folders, _, _, _ = _collect(FIXTURES_DIR)
    names = {f["name"] for f in _all_files(folders)}
    assert "hevc_skip.mkv" not in names


def test_walk_finds_all_video_extensions():
    """.mp4 file found alongside .mkv files."""
    folders, _, _, _ = _collect(FIXTURES_DIR)
    names = {f["name"] for f in _all_files(folders)}
    mp4_names = {n for n in names if n.endswith(".mp4")}
    mkv_names = {n for n in names if n.endswith(".mkv")}
    assert len(mp4_names) >= 1
    assert len(mkv_names) >= 1


def test_walk_streams_populated():
    """streams.video.codec is 'H264' on h264_short.mkv."""
    folders, _, _, _ = _collect(FIXTURES_DIR)
    files = _all_files(folders)
    short = next(f for f in files if f["name"] == "h264_short.mkv")
    assert short["streams"]["video"]["codec"] == "H264"
    assert short["streams"]["video"]["resolution"] != "unknown"


def test_walk_hi10_flagged():
    """h264_hi10.mkv has is_hi10 == True."""
    folders, _, _, _ = _collect(FIXTURES_DIR)
    files = _all_files(folders)
    hi10 = next(f for f in files if f["name"] == "h264_hi10.mkv")
    assert hi10["is_hi10"] is True


def test_walk_done_event():
    """Final event is type='done' with total_files == 6."""
    folders, done, _, _ = _collect(FIXTURES_DIR)
    assert done is not None
    assert done["type"] == "done"
    assert done["total_files"] == 6
    assert done["total_mb"] > 0


# ---------------------------------------------------------------------------
# scanner.walk — folder event shape
# ---------------------------------------------------------------------------

def test_walk_folder_events(tmp_path):
    """Two subdirectories each produce one folder event with correct rel path."""
    sub_a = tmp_path / "ShowA"
    sub_b = tmp_path / "ShowB"
    sub_a.mkdir()
    sub_b.mkdir()
    shutil.copy(FIXTURES_DIR / "h264_short.mkv",   sub_a / "ep01.mkv")
    shutil.copy(FIXTURES_DIR / "h264_mp4_aac.mp4", sub_b / "ep02.mp4")

    folders, done, _, _ = _collect(tmp_path)

    folder_names = {ev["folder"] for ev in folders}
    assert "ShowA" in folder_names
    assert "ShowB" in folder_names
    assert done["total_files"] == 2


# ---------------------------------------------------------------------------
# scanner.walk — corrupt / empty file handling
# ---------------------------------------------------------------------------

def test_walk_corrupt_file_emits_warning(tmp_path):
    """A zero-byte .mkv yields a warning event; walk continues normally."""
    # Real file alongside the bad one so the folder is still yielded
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", tmp_path / "good.mkv")
    (tmp_path / "bad.mkv").write_bytes(b"")

    folders, done, warnings, _ = _collect(tmp_path)

    # Warning for the empty file
    assert any("bad.mkv" in w["path"] for w in warnings)
    # Good file still scanned
    names = {f["name"] for f in _all_files(folders)}
    assert "good.mkv" in names
    assert done["total_files"] == 1


# ---------------------------------------------------------------------------
# scanner.walk — DB skip / requeue behaviour
# ---------------------------------------------------------------------------

def test_walk_skips_db_done(tmp_path, fresh_db):
    """File with status='done' in DB is silently excluded from folder events."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    mtime  = dest.stat().st_mtime
    rec_id = db.upsert_pending(str(dest), mtime)
    db.mark_running(rec_id, "2026-01-01T00:00:00Z")
    db.mark_done(
        rec_id,
        str(tmp_path / "converted" / "h264_short.mkv"),
        output_size_mb=0.5,
        saved_mb=0.7,
        saved_pct=58,
        completed_at="2026-01-01T00:01:00Z",
    )

    folders, done, _, _ = _collect(tmp_path)
    assert done["total_files"] == 0
    assert folders == []


def test_walk_requeues_replaced_file(tmp_path, fresh_db):
    """Same path but different mtime is treated as a new file."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    mtime  = dest.stat().st_mtime
    rec_id = db.upsert_pending(str(dest), mtime)
    db.mark_running(rec_id, "2026-01-01T00:00:00Z")
    db.mark_done(
        rec_id,
        str(tmp_path / "converted" / "h264_short.mkv"),
        output_size_mb=0.5,
        saved_mb=0.7,
        saved_pct=58,
        completed_at="2026-01-01T00:01:00Z",
    )

    # Simulate in-place replacement by nudging mtime forward
    new_mtime = mtime + 1.0
    os.utime(str(dest), (new_mtime, new_mtime))

    folders, done, _, _ = _collect(tmp_path)
    assert done["total_files"] == 1, "New mtime should bypass DB skip"
    assert len(folders) == 1


def test_walk_running_emits_warning(tmp_path, fresh_db):
    """File with status='running' in DB emits a warning and is not yielded."""
    dest = tmp_path / "h264_short.mkv"
    shutil.copy(FIXTURES_DIR / "h264_short.mkv", dest)

    mtime  = dest.stat().st_mtime
    rec_id = db.upsert_pending(str(dest), mtime)
    db.mark_running(rec_id, "2026-01-01T00:00:00Z")

    folders, done, warnings, _ = _collect(tmp_path)
    assert done["total_files"] == 0
    assert folders == []
    assert any(str(dest).replace("\\", "/") in w["path"].replace("\\", "/")
               for w in warnings)


# ---------------------------------------------------------------------------
# scanner.walk — error handling
# ---------------------------------------------------------------------------

def test_walk_invalid_root():
    """Non-existent root yields a single error event and no folder events."""
    folders, done, warnings, errors = _collect("/nonexistent/path/xyz_abc")
    assert errors != []
    assert folders == []
    assert done is None


# ---------------------------------------------------------------------------
# Flask API route tests
# ---------------------------------------------------------------------------

@pytest.fixture
def client():
    # Import app after db.init_db has been called by fresh_db (autouse),
    # so app.py's module-level db.init_db(DB_PATH) is overridden for test.
    import app as flask_app
    flask_app.app.testing = True
    with flask_app.app.test_client() as c:
        yield c


def test_api_scan_invalid_path(client):
    """GET /api/scan with a missing path returns 400."""
    resp = client.get("/api/scan?path=/nonexistent/path/xyz_abc_123")
    assert resp.status_code == 400


def test_api_scan_no_path_param(client):
    """GET /api/scan with no path param returns 400."""
    resp = client.get("/api/scan")
    assert resp.status_code == 400


def test_api_scan_sse_content_type(client):
    """GET /api/scan on a valid directory returns text/event-stream."""
    resp = client.get(f"/api/scan?path={FIXTURES_DIR!s}")
    assert resp.status_code == 200
    assert "text/event-stream" in resp.content_type


# ---------------------------------------------------------------------------
# AV1 codec skip
# ---------------------------------------------------------------------------

def test_walk_skips_av1(tmp_path):
    """Files whose first video stream is AV1 are excluded (already optimal)."""
    from unittest.mock import patch

    av1_file = tmp_path / "av1_video.mkv"
    av1_file.write_bytes(b"\x00" * 100)   # dummy bytes — ffprobe is mocked

    av1_probe_result = {
        "streams": [{
            "codec_type": "video",
            "codec_name": "av1",
            "width": 1920,
            "height": 1080,
            "r_frame_rate": "24/1",
            "profile": "",
            "pix_fmt": "yuv420p",
            "bits_per_raw_sample": "8",
        }],
        "format": {"duration": "120.0", "bit_rate": "5000000"},
    }

    with patch("scanner._ffprobe", return_value=av1_probe_result):
        folders, done, warnings, errors = _collect(str(tmp_path))

    all_names = {f["name"] for f in _all_files(folders)}
    assert "av1_video.mkv" not in all_names, (
        "AV1 file should have been skipped but appeared in scan results"
    )
